### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by AlexD81** [glifxyz/ComfyUI-GlifNodes#1]
0.0 seconds (IMPORT FAILED): C:\Users\*****\ComfyUI\custom_nodes\ComfyUI-GlifNodes

It was installed via manager. Tried to reinstal a couple of times, but it doesn't helps.    
ComfyUI is updated to most recent version

**Comment by rvorias** [comment]
Hey @AlexD81 , thanks for your issue report.

Did you get any more error information?

**Comment by rvorias** [comment]
I think there was a rogue import, could you try again?

**Comment by AlexD81** [comment]
> I think there was a rogue import, could you try again?

thanks for quick ansver,   Tried again,  but problem is the same.  Re-update comfy ui  as well,  didn't help.    I'm not a dev, don't know where to find more error messages or other details, import failled - only what I see

**Comment by rvorias** [comment]
Just tried to reinstall via the manager as well, but not seeing any import errors!

I assume you are using windows? I only tested it on Linux.

**Comment by AlexD81** [comment]
> Just tried to reinstall via the manager as well, but not seeing any import errors!
> 
> I assume you are using windows? I only tested it on Linux.

yes, I use windows

**Comment by rvorias** [comment]
closing this but please let me know if this isn't fixed yet

**Comment by AconexOfficial** [comment]
Hi, I also can't seem to be able to get Comfy to import the nodes. Tried to install both manually aswell as through ComfyUI Manager.

I'm using ComfyUI Portable and Window 11 btw.

This is the error I get:

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
    from diffusers import ConsistencyDecoderVAE
ImportError: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)
```

**Comment by rvorias** [comment]
> Hi, I also can't seem to be able to get Comfy to import the nodes. Tried to install both manually aswell as through ComfyUI Manager.
> 
> I'm using ComfyUI Portable and Window 11 btw.
> 
> This is the error I get:
> 
> ```
> Traceback (most recent call last):
>   File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
>     from diffusers import ConsistencyDecoderVAE
> ImportError: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)
> 
> Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)
> ```

Hi! Which version of diffusers are you using?

**Comment by AconexOfficial** [comment]
> > Hi, I also can't seem to be able to get Comfy to import the nodes. Tried to install both manually aswell as through ComfyUI Manager.
> > I'm using ComfyUI Portable and Window 11 btw.
> > This is the error I get:
> > ```
> > Traceback (most recent call last):
> >   File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
> >     module_spec.loader.exec_module(module)
> >   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> >   File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
> >     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
> >   File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
> >     from diffusers import ConsistencyDecoderVAE
> > ImportError: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)
> > 
> > Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)
> > ```
> 
> Hi! Which version of diffusers are you using?


I have diffusers 0.24.0 installed

Requirement already satisfied: diffusers==0.24.0 in c:\users\...\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.24.0)

**Comment by rvorias** [comment]
Will look at this the next time I have a chance. Can you try installing the latest diffusers?

**Comment by AconexOfficial** [comment]
> Will look at this the next time I have a chance. Can you try installing the latest diffusers?

I tried with 0.29.2 now, import still failed unfortunately

**Comment by rvorias** [comment]
Ok, from a terminal, can you run the following:

`python`
and then
`import diffusers; print(diffusers.__version__); from diffusers import ConsistencyDecoderVAE`

For me this gives:

`0.29.2` and no errors.

Using 0.24.0 and the same command gives me

`0.24.0` and no errors.

I'm afraid you have some mismatch with your env and/or you diffusers version.

**Comment by AconexOfficial** [comment]
This is what I get, when I run the command.
![image](https://github.com/glifxyz/ComfyUI-GlifNodes/assets/66433136/732078aa-9b0d-4180-bb1e-3cda6586a8a5)

Could it possibly have to do with my ComfyUI being the Portable version?

**Comment by rvorias** [comment]
> This is what I get, when I run the command. ![image](https://private-user-images.githubusercontent.com/66433136/345427487-732078aa-9b0d-4180-bb1e-3cda6586a8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTE0NzIsIm5iZiI6MTcyMDAxMTE3MiwicGF0aCI6Ii82NjQzMzEzNi8zNDU0Mjc0ODctNzMyMDc4YWEtOWIwZC00MTgwLWJiMWUtM2NkYTY1ODZhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYjcwYTk5OWRjYTUwYTY2YTUwMWU4YmQ4NTI4NTNjNWYyZDUwM2Y4OTgyNzllYzA0NWI0MmRiMDJmNmZkYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tryq4REI-Is2XmwMM5JooeWUHS1OVe228ehCxlkY41Q)
> 
> Could it possibly have to do with my ComfyUI being the Portable version?

And no error? Then you've successfully imported ConsistencyDecoderVAE from diffusers!

It might indeed be the portable version and how it managed its packages. Can you find a way to uninstall and install diffusers in that specific environment?

**Comment by AconexOfficial** [comment]
> > This is what I get, when I run the command. ![image](https://private-user-images.githubusercontent.com/66433136/345427487-732078aa-9b0d-4180-bb1e-3cda6586a8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTE0NzIsIm5iZiI6MTcyMDAxMTE3MiwicGF0aCI6Ii82NjQzMzEzNi8zNDU0Mjc0ODctNzMyMDc4YWEtOWIwZC00MTgwLWJiMWUtM2NkYTY1ODZhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYjcwYTk5OWRjYTUwYTY2YTUwMWU4YmQ4NTI4NTNjNWYyZDUwM2Y4OTgyNzllYzA0NWI0MmRiMDJmNmZkYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tryq4REI-Is2XmwMM5JooeWUHS1OVe228ehCxlkY41Q)
> > Could it possibly have to do with my ComfyUI being the Portable version?
> 
> And no error? Then you've successfully imported ConsistencyDecoderVAE from diffusers!
> 
> It might indeed be the portable version and how it managed its packages. Can you find a way to uninstall and install diffusers in that specific environment?

It does import your nodes now.
I checked the diffusers version inside the portable installation and it was 0.21.4, contrary to the global python installation.
I upgraded it using this command inside the ComfyUI_windows_portable folder: 
`python_embeded\python.exe -m pip install --upgrade diffusers`
